import './v05.css';

type User={id:string;username:string;displayName:string;role:string;facilityId:string|null;patientId?:string};
type V05View='workspace'|'emergency'|'identity'|'watch'|'commandv05'|'population'|'exchange';

const api=async(path:string,init?:RequestInit)=>{const res=await fetch(path,{credentials:'include',headers:{'Content-Type':'application/json',...(init?.headers||{})},...init});const body=await res.json().catch(()=>({}));if(!res.ok){const e:any=new Error(body.error||`Request failed (${res.status})`);e.body=body;throw e}return body};
const esc=(v:any)=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]||c));
const fmt=(iso:string)=>{try{return new Date(iso).toLocaleString('en-ZA',{dateStyle:'medium',timeStyle:'short'})}catch{return iso}};
const clinical=['ADMIN','CLINICIAN','SPECIALIST','NURSE'];
const professional=['ADMIN','CLINICIAN','SPECIALIST','NURSE','COORDINATOR','PHARMACIST','LAB_TECH','PATIENT_NAVIGATOR'];
const management=['ADMIN','MANAGER','AUDITOR'];
let currentUser:User|null=null;
let currentView:V05View|null=null;
let release:any=null;

function content(){return document.querySelector<HTMLElement>('main.content')}
function nav(){return document.querySelector<HTMLElement>('.topbar nav')}
function shell(title:string,eyebrow:string,desc:string,body:string,badge='v0.5 Federated Platform'){
  return `<section class="v05-shell"><div class="v05-hero"><div><span class="v05-eyebrow">${esc(eyebrow)}</span><h1>${esc(title)}</h1><p>${esc(desc)}</p></div><span class="v05-badge">${esc(badge)}</span></div>${body}</section>`;
}
function errorBox(e:any){return `<div class="v05-alert danger"><b>Unable to load this CarePath module.</b><br>${esc(e?.message||e)}</div>`}
function kpi(label:string,value:any){return `<div class="v05-kpi"><b>${esc(value)}</b><span>${esc(label)}</span></div>`}
function chip(text:string,tone=''){return `<span class="v05-chip ${tone}">${esc(text)}</span>`}
function findPatientName(p:any){return p.name||p.patientName||p.syntheticId||p.id}

async function renderWorkspace(){
  const root=content();if(!root)return;root.innerHTML=shell('Healthcare Professional Workspace','MY WORKSPACE','A role-specific worklist for patients, referrals, appointments, hand-offs, tasks and follow-up.','<div class="v05-empty">Loading authorised workspace…</div>');
  try{const d=await api('/api/v05/workspace');const tasks=(d.tasks||[]).map((t:any)=>`<div class="v05-row"><div><b>${esc(t.title)}</b><span>${esc(t.detail)}</span><small>${esc(t.patientName||'Operational task')} • due ${fmt(t.dueAt)}</small></div>${chip(t.priority,t.priority==='HIGH'?'critical':'')}${chip(t.status,t.status==='DONE'?'good':'')}</div>`).join('')||'<div class="v05-empty">No tasks in this authorised worklist.</div>';const handoffs=(d.handOffs||[]).map((h:any)=>`<div class="v05-row"><div><b>${esc(h.patientName)} — ${esc(h.service)}</b><span>Owner: ${esc(h.owner)}</span></div>${chip(h.status)}</div>`).join('')||'<div class="v05-empty">No active hand-offs.</div>';root.innerHTML=shell('Healthcare Professional Workspace','MY WORKSPACE','A role-specific worklist for patients, referrals, appointments, hand-offs, tasks and follow-up.',`<div class="v05-kpis">${kpi('Authorised patients',d.today.patients)}${kpi('Open referrals',d.today.openReferrals)}${kpi('Active appointments',d.today.appointments)}${kpi('High-priority tasks',d.today.highPriorityTasks)}</div><div class="v05-grid"><section class="v05-card half"><h2>My tasks</h2><div class="v05-list">${tasks}</div></section><section class="v05-card half"><h2>Clinical hand-offs</h2><div class="v05-list">${handoffs}</div></section><section class="v05-card full"><h2>Results awaiting review</h2><div class="v05-list">${(d.resultsAwaiting||[]).map((r:any)=>`<div class="v05-row"><div><b>${esc(r.patientName)}</b><span>${esc(r.results?.map((x:any)=>x.label).join(', ')||'Result context')}</span></div>${chip('Source-grounded')}</div>`).join('')||'<div class="v05-empty">No result-review items.</div>'}</div></section></div>`)}catch(e){root.innerHTML=shell('Healthcare Professional Workspace','MY WORKSPACE','Authorised worklist.',errorBox(e))}
}

async function renderEmergency(){
  const root=content();if(!root)return;root.innerHTML=shell('Emergency Patient Access','BREAK GLASS','Retrieve a minimum-necessary synthetic emergency summary only after explicit reason capture and demo re-authentication.','<div class="v05-empty">Loading emergency access controls…</div>','High-visibility audited access');
  try{const ps=await api('/api/patients');const options=(ps.patients||[]).slice(0,120).map((p:any)=>`<option value="${esc(p.id)}">${esc(p.firstName)} ${esc(p.surname)} — ${esc(p.syntheticId)}</option>`).join('');const log=await api('/api/v05/breakglass');root.innerHTML=shell('Emergency Patient Access','BREAK GLASS','Retrieve a minimum-necessary synthetic emergency summary only after explicit reason capture and demo re-authentication.',`<div class="v05-alert danger"><b>Emergency access does not silently bypass security.</b><br>Reason, user, facility, re-authentication, expiry and every sensitive read are auditable.</div><div class="v05-grid"><section class="v05-card half"><h2>Request emergency access</h2><form id="v05-breakglass-form" class="v05-form"><label class="full">Patient<select name="patientId">${options}</select></label><label class="full">Emergency reason<textarea name="reason" required placeholder="e.g. Patient is unconscious and critical allergy/medication history is required for emergency continuity of care."></textarea></label><label class="full">Re-authenticate with demo password<input name="password" type="password" required placeholder="CarePath!2026"/></label><button class="v05-button" type="submit">Break Glass — 15 minutes</button></form><div id="v05-emergency-result"></div></section><section class="v05-card half"><h2>Emergency access history</h2><div class="v05-list">${(log.events||[]).map((g:any)=>`<div class="v05-row"><div><b>${esc(g.patientName)}</b><span>${esc(g.reason)}</span><small>${esc(g.userName)} • ${fmt(g.createdAt)} • expires ${fmt(g.expiresAt)}</small></div>${chip(g.status,g.status==='ACTIVE'?'critical':'')}</div>`).join('')||'<div class="v05-empty">No Break Glass events for this scope.</div>'}</div></section></div>`,'Audited • Time-limited • Minimum necessary');document.querySelector<HTMLFormElement>('#v05-breakglass-form')?.addEventListener('submit',async e=>{e.preventDefault();const form=e.currentTarget;const fd=new FormData(form);const target=document.querySelector<HTMLElement>('#v05-emergency-result');if(!target)return;target.innerHTML='<div class="v05-alert">Requesting governed access…</div>';try{const d=await api('/api/v05/breakglass',{method:'POST',body:JSON.stringify({patientId:fd.get('patientId'),reason:fd.get('reason'),password:fd.get('password')})});target.innerHTML=`<div class="v05-alert good"><b>Emergency grant active until ${fmt(d.grant.expiresAt)}</b></div>${emergencySummaryHtml(d.summary)}`;await injectVersion()}catch(err:any){target.innerHTML=errorBox(err)}})}catch(e){root.innerHTML=shell('Emergency Patient Access','BREAK GLASS','Governed emergency access.',errorBox(e))}
}
function emergencySummaryHtml(s:any){if(!s)return '';return `<div class="v05-card full" style="margin-top:12px"><h3>${esc(s.patient.name)} — emergency summary</h3><div class="v05-two-col"><div><b>Allergies</b>${(s.critical.allergies||[]).map((x:any)=>`<p>${chip(x.label,'critical')}<small>${esc(x.source)}</small></p>`).join('')||'<p>None recorded.</p>'}<b>Conditions</b>${(s.critical.conditions||[]).map((x:any)=>`<p>${chip(x.label,'warning')}<small>${esc(x.source)}</small></p>`).join('')}</div><div><b>Current medication</b>${(s.critical.medications||[]).map((x:any)=>`<p>${chip(x.label,'good')}<small>${esc(x.detail||'')} • ${esc(x.source)}</small></p>`).join('')||'<p>None recorded.</p>'}</div></div><p><small>${esc(s.note)}</small></p></div>`}

async function renderIdentity(){
  const root=content();if(!root)return;root.innerHTML=shell('Consent & Identity Centre','IDENTITY + ACCESS','Resolve federated patient identifiers, review source links and manage patient sharing preferences without inventing a new national identifier.','<div class="v05-empty">Loading patient identity index…</div>');
  try{const d=await api('/api/v05/identity');const rows=(d.patients||[]).map((p:any)=>`<tr><td><b>${esc(p.name)}</b><small>${esc(p.syntheticId)}</small></td><td>${esc(p.dateOfBirth)}</td><td>${p.identifiers} linked demo identifiers</td><td><button class="v05-button secondary v05-id-open" data-id="${esc(p.id)}">Open</button></td></tr>`).join('');root.innerHTML=shell('Consent & Identity Centre','IDENTITY + ACCESS','Resolve federated patient identifiers, review source links and manage patient sharing preferences without inventing a new national identifier.',`<div class="v05-alert"><b>Architecture boundary:</b> CarePath uses an MPI abstraction. Production matching requires an approved authoritative identity service, governed merge/unmerge and no name-only matching.</div><div class="v05-grid"><section class="v05-card full"><div class="v05-toolbar"><label>Search identity<input id="v05-id-search" placeholder="Name or synthetic ID"/></label></div><div class="v05-table-wrap"><table class="v05-table"><thead><tr><th>Patient</th><th>Date of birth</th><th>Federated identifiers</th><th>Action</th></tr></thead><tbody id="v05-id-body">${rows}</tbody></table></div></section><section id="v05-id-detail" class="v05-card full"><div class="v05-empty">Select a patient to inspect source identifiers, consent and governance context.</div></section></div>`);const bind=()=>document.querySelectorAll<HTMLButtonElement>('.v05-id-open').forEach(b=>b.onclick=()=>openIdentity(b.dataset.id||''));bind();let timer:any;document.querySelector<HTMLInputElement>('#v05-id-search')?.addEventListener('input',e=>{clearTimeout(timer);timer=setTimeout(async()=>{const q=(e.target as HTMLInputElement).value;const x=await api(`/api/v05/identity?q=${encodeURIComponent(q)}`);const body=document.querySelector('#v05-id-body');if(body){body.innerHTML=(x.patients||[]).map((p:any)=>`<tr><td><b>${esc(p.name)}</b><small>${esc(p.syntheticId)}</small></td><td>${esc(p.dateOfBirth)}</td><td>${p.identifiers} linked demo identifiers</td><td><button class="v05-button secondary v05-id-open" data-id="${esc(p.id)}">Open</button></td></tr>`).join('');bind()}},250)})}catch(e){root.innerHTML=shell('Consent & Identity Centre','IDENTITY + ACCESS','Federated patient identity.',errorBox(e))}
}
async function openIdentity(id:string){const target=document.querySelector<HTMLElement>('#v05-id-detail');if(!target)return;target.innerHTML='<div class="v05-empty">Loading identity and consent…</div>';try{const [ident,consent,plans,docs]=await Promise.all([api(`/api/v05/identity/${id}`),api(`/api/v05/consent/${id}`),api(`/api/v05/care-plans/${id}`),api(`/api/v05/documents/${id}`)]);target.innerHTML=`<h2>${esc(ident.patient.name)}</h2><p>${esc(ident.patient.syntheticId)} • ${esc(ident.matching.status)} • ${esc(ident.matching.method)}</p><div class="v05-grid"><div class="v05-card half"><h3>Linked source identifiers</h3><div class="v05-list">${ident.identifiers.map((x:any)=>`<div class="v05-row"><div><b>${esc(x.system)}</b><span>${esc(x.value)}</span></div>${chip(x.status,x.authoritative?'good':'')}</div>`).join('')}</div></div><div class="v05-card half"><h3>Consent / sharing context</h3>${(consent.records||[]).map((c:any)=>`<div class="v05-row"><div><b>${esc(c.purpose)} — ${esc(c.status)}</b><span>Care team sharing: ${c.shareWithCareTeam?'Yes':'No'} • Messaging: ${c.allowPatientMessaging?'Yes':'No'} • Proxy: ${c.allowCaregiverProxy?'Yes':'No'}</span><small>Updated ${fmt(c.updatedAt)} by ${esc(c.updatedBy)}</small></div></div>`).join('')}</div><div class="v05-card half"><h3>Care plans</h3>${(plans.carePlans||[]).map((p:any)=>`<div class="v05-row"><div><b>${esc(p.title)}</b><span>${esc(p.goal)}</span><small>${esc(p.owner)} • review ${fmt(p.reviewAt)}</small></div>${chip(p.status,p.status==='ACTIVE'?'good':'warning')}</div>`).join('')||'<div class="v05-empty">No plan recorded.</div>'}</div><div class="v05-card half"><h3>Documents & imaging metadata</h3>${(docs.documents||[]).map((d:any)=>`<div class="v05-row"><div><b>${esc(d.title)}</b><span>${esc(d.type.replaceAll('_',' '))} • ${esc(d.sourceFacilityName)}</span><small>${fmt(d.recordedAt)}</small></div>${chip(d.status,'good')}</div>`).join('')||'<div class="v05-empty">No documents recorded.</div>'}</div></div>`}catch(e){target.innerHTML=errorBox(e)}}

async function renderWatch(){const root=content();if(!root)return;root.innerHTML=shell('CarePath Watch™','EARLY WARNING','Explainable operational early warning for referral leakage, missed appointments, missing feedback and capacity constraints.','<div class="v05-empty">Evaluating configured rules…</div>');try{const d=await api('/api/v05/watch');const rows=(d.findings||[]).map((f:any)=>`<div class="v05-row"><div><b>${esc(f.type.replaceAll('_',' '))}</b><span>${esc(f.evidence)}</span><small>Rule: ${esc(f.rule)} • Owner: ${esc(f.owner)}</small><small>Next permitted action: ${esc(f.recommendedAction)}</small></div>${chip(f.severity,f.severity==='CRITICAL'?'critical':f.severity==='WARNING'?'warning':'')}</div>`).join('');root.innerHTML=shell('CarePath Watch™','EARLY WARNING','Explainable operational early warning for referral leakage, missed appointments, missing feedback and capacity constraints.',`<div class="v05-kpis">${kpi('Critical',d.summary.critical)}${kpi('Warnings',d.summary.warning)}${kpi('Informational',d.summary.info)}</div><div class="v05-alert"><b>Clinical safety boundary:</b> ${esc(d.boundary)}</div><section class="v05-card full"><h2>Current findings</h2><div class="v05-list">${rows||'<div class="v05-empty">No findings.</div>'}</div></section>`,'Rules are explainable • no diagnosis')}catch(e){root.innerHTML=shell('CarePath Watch™','EARLY WARNING','Explainable pathway monitoring.',errorBox(e))}}

async function renderCommandV05(province?:string){const root=content();if(!root)return;root.innerHTML=shell('National CarePath Command Centre','NATIONAL → PROVINCE → DISTRICT → FACILITY','Aggregated operational visibility over patient flow, referrals, capacity, SLA exceptions and unresolved journeys.','<div class="v05-empty">Loading de-identified national operating view…</div>');try{const d=await api(province?`/api/v05/command?level=province&province=${encodeURIComponent(province)}`:'/api/v05/command?level=country');if(!province){const cards=(d.children||[]).map((p:any)=>`<button class="v05-scope-card v05-province" data-province="${esc(p.province)}"><b>${esc(p.province)}</b><small>${p.facilities} facilities • ${p.openReferrals} open referrals</small><small>${p.availableBeds} beds available* • ${p.slaBreaches} SLA exceptions</small></button>`).join('');root.innerHTML=shell('National CarePath Command Centre','NATIONAL → PROVINCE → DISTRICT → FACILITY','Aggregated operational visibility over patient flow, referrals, capacity, SLA exceptions and unresolved journeys.',`<div class="v05-kpis">${kpi('Synthetic patients',d.metrics.patients)}${kpi('Facilities',d.metrics.facilities)}${kpi('Open referrals',d.metrics.openReferrals)}${kpi('Appointments',d.metrics.appointments)}${kpi('Beds available*',d.metrics.availableBeds)}${kpi('SLA breaches',d.metrics.slaBreaches)}</div><section class="v05-card full"><h2>Provincial drill-down</h2><div class="v05-grid">${cards}</div><p><small>* Synthetic capacity; not a live national hospital feed.</small></p></section>`);document.querySelectorAll<HTMLButtonElement>('.v05-province').forEach(b=>b.onclick=()=>renderCommandV05(b.dataset.province))}else{const districts=(d.children||[]).map((x:any)=>`<div class="v05-row"><div><b>${esc(x.district)}</b><span>${x.facilities} facilities • ${x.openReferrals} open referrals • ${x.availableBeds} beds available*</span></div>${x.slaBreaches?chip(`${x.slaBreaches} SLA`, 'warning'):chip('No SLA flag','good')}</div>`).join('');const fs=(d.facilities||[]).map((f:any)=>`<div class="v05-row"><div><b>${esc(f.name)}</b><span>${esc(f.city||f.district)} • ${esc(f.type)}</span></div>${chip(`${f.availableBeds} beds`,f.availableBeds===0?'critical':f.availableBeds<5?'warning':'good')}</div>`).join('');root.innerHTML=shell(`${province} Command Centre`,'PROVINCIAL DRILL-DOWN','Aggregated province-to-district-to-facility operational view.',`<button id="v05-command-back" class="v05-button secondary">← National view</button><div class="v05-grid"><section class="v05-card half"><h2>Districts</h2><div class="v05-list">${districts}</div></section><section class="v05-card half"><h2>Facilities</h2><div class="v05-list">${fs}</div></section></div>`);document.querySelector<HTMLButtonElement>('#v05-command-back')!.onclick=()=>renderCommandV05()}}catch(e){root.innerHTML=shell('National CarePath Command Centre','COMMAND','Aggregated operational view.',errorBox(e))}}

async function renderPopulation(){const root=content();if(!root)return;root.innerHTML=shell('Population Health Intelligence','AGGREGATED + DE-IDENTIFIED','Operational intelligence for health authorities without exposing individual patient identity where it is not required.','<div class="v05-empty">Loading aggregated synthetic intelligence…</div>');try{const d=await api('/api/v05/population');const serviceRows=(d.services||[]).slice(0,12).map((s:any)=>`<tr><td><b>${esc(s.service)}</b></td><td>${s.referrals}</td><td>${s.open}</td><td>${s.missedAppointments}</td></tr>`).join('');const provinceRows=(d.provinces||[]).map((p:any)=>`<tr><td><b>${esc(p.province)}</b></td><td>${p.facilities}</td><td>${p.openReferrals}</td><td>${p.availableBeds}</td><td>${p.slaBreaches}</td></tr>`).join('');root.innerHTML=shell('Population Health Intelligence','AGGREGATED + DE-IDENTIFIED','Operational intelligence for health authorities without exposing individual patient identity where it is not required.',`<div class="v05-kpis">${kpi('Patients in synthetic cohort',d.patients)}${kpi('Facilities',d.facilities)}${kpi('Referrals',d.referrals)}${kpi('Appointments',d.appointments)}</div><div class="v05-alert"><b>Governance:</b> ${esc(d.disclaimer)}</div><div class="v05-grid"><section class="v05-card half"><h2>Province operations</h2><div class="v05-table-wrap"><table class="v05-table"><thead><tr><th>Province</th><th>Facilities</th><th>Open referrals</th><th>Beds*</th><th>SLA</th></tr></thead><tbody>${provinceRows}</tbody></table></div></section><section class="v05-card half"><h2>Service demand</h2><div class="v05-table-wrap"><table class="v05-table"><thead><tr><th>Service</th><th>Referrals</th><th>Open</th><th>No-show</th></tr></thead><tbody>${serviceRows}</tbody></table></div></section><section class="v05-card full"><h2>Observed synthetic outcomes</h2><div class="v05-kpis">${kpi('Recovered',d.outcomes.recovered)}${kpi('Improved',d.outcomes.improved)}${kpi('Ongoing',d.outcomes.ongoing)}${kpi('Deceased',d.outcomes.deceased)}${kpi('Unknown',d.outcomes.unknown)}</div><p><small>These observed synthetic values are not risk-adjusted and must not be used as a hospital-quality ranking.</small></p></section></div>`)}catch(e){root.innerHTML=shell('Population Health Intelligence','POPULATION','Aggregated operational intelligence.',errorBox(e))}}

async function renderExchange(){const root=content();if(!root)return;root.innerHTML=shell('CarePath Exchange Gateway','INTEROPERABILITY','A demonstrable standards-aware gateway showing how existing source systems contribute to a federated longitudinal record.','<div class="v05-empty">Loading mock interoperability contracts…</div>');try{const [sources,cap]=await Promise.all([api('/api/v05/exchange/sources'),api('/api/v05/fhir/metadata')]);const src=(sources.sources||[]).map((s:any)=>`<div class="v05-row"><div><b>${esc(s.name)}</b><span>${esc(s.type)} • ${esc(s.resources.join(', '))}</span></div>${chip(s.mode,'warning')}</div>`).join('');root.innerHTML=shell('CarePath Exchange Gateway','INTEROPERABILITY','A demonstrable standards-aware gateway showing how existing source systems contribute to a federated longitudinal record.',`<div class="v05-alert"><b>No fabricated integration claims:</b> ${esc(sources.warning)}</div><div class="v05-source-flow"><div class="v05-source-box">Public / private source systems</div><div class="v05-arrow">→</div><div class="v05-source-box">CarePath Exchange<br><small>FHIR-style adapter layer</small></div><div class="v05-arrow">→</div><div class="v05-source-box">OneRecord + Journey<br><small>provenance preserved</small></div></div><div class="v05-grid"><section class="v05-card half"><h2>Mock source adapters</h2><div class="v05-list">${src}</div></section><section class="v05-card half"><h2>FHIR capability demo</h2><p><b>${esc(cap.software?.name)}</b> v${esc(cap.software?.version)}</p><p>FHIR version: ${esc(cap.fhirVersion)} • JSON</p><div>${(cap.rest?.[0]?.resource||[]).map((r:any)=>chip(r.type,'good')).join('')}</div><p><small>${esc(cap.implementation?.description)}</small></p><div class="v05-alert">Formal national-profile conformance is not claimed until a selected implementation guide is implemented and tested.</div></section></div>`)}catch(e){root.innerHTML=shell('CarePath Exchange Gateway','INTEROPERABILITY','Standards-aware adapters.',errorBox(e))}}

const renderers:Record<V05View,()=>Promise<void>>={workspace:renderWorkspace,emergency:renderEmergency,identity:renderIdentity,watch:renderWatch,commandv05:()=>renderCommandV05(),population:renderPopulation,exchange:renderExchange};
async function openView(view:V05View){currentView=view;document.querySelectorAll('.v05-nav button').forEach(b=>b.classList.toggle('active',(b as HTMLElement).dataset.v05===view));await renderers[view]();window.scrollTo({top:0,behavior:'smooth'})}

function injectNav(){const host=nav();if(!host||!currentUser)return;if(host.querySelector('.v05-nav'))return;const wrap=document.createElement('span');wrap.className='v05-nav';const items:{id:V05View;label:string;roles?:string[]}[]=[{id:'workspace',label:'My Workspace',roles:professional},{id:'emergency',label:'Emergency',roles:clinical},{id:'identity',label:'Consent & Identity'},{id:'watch',label:'CarePath Watch'},{id:'commandv05',label:'National Command',roles:management},{id:'population',label:'Population Health',roles:management},{id:'exchange',label:'Exchange',roles:['ADMIN','MANAGER','AUDITOR','CLINICIAN','SPECIALIST']}];items.filter(i=>!i.roles||i.roles.includes(currentUser!.role)).forEach(i=>{const b=document.createElement('button');b.textContent=i.label;b.dataset.v05=i.id;b.onclick=()=>openView(i.id);wrap.appendChild(b)});host.appendChild(wrap)}

async function injectRecordExtensions(){if(!currentUser)return;const hero=document.querySelector<HTMLElement>('.patient-hero');const layout=document.querySelector<HTMLElement>('.record-layout');if(!hero||!layout||document.querySelector('.v05-record-extension'))return;const title=hero.querySelector('h1')?.textContent?.trim();if(!title)return;try{const list=await api('/api/patients');const p=(list.patients||[]).find((x:any)=>`${x.firstName} ${x.surname}`===title);if(!p)return;const [plans,docs,identity]=await Promise.all([api(`/api/v05/care-plans/${p.id}`),api(`/api/v05/documents/${p.id}`),api(`/api/v05/identity/${p.id}`)]);const box=document.createElement('section');box.className='v05-record-extension';box.innerHTML=`<header><div><span class="v05-eyebrow">V0.5 FEDERATED RECORD EXTENSIONS</span><h3>Care plans, documents & source identity</h3></div>${chip('Provenance retained','good')}</header><div class="v05-two-col"><div><b>Care plans</b>${(plans.carePlans||[]).map((x:any)=>`<div class="v05-row"><div><b>${esc(x.title)}</b><span>${esc(x.goal)}</span><small>Review ${fmt(x.reviewAt)} • ${esc(x.facilityName)}</small></div>${chip(x.status,x.status==='ACTIVE'?'good':'warning')}</div>`).join('')||'<div class="v05-empty">No active plan.</div>'}</div><div><b>Documents & imaging reports</b>${(docs.documents||[]).map((x:any)=>`<div class="v05-row"><div><b>${esc(x.title)}</b><span>${esc(x.type.replaceAll('_',' '))} • ${esc(x.sourceFacilityName)}</span><small>${fmt(x.recordedAt)}</small></div>${chip(x.status,'good')}</div>`).join('')||'<div class="v05-empty">No documents.</div>'}</div></div><p><small>${identity.identifiers?.length||0} federated source identifiers are linked to this synthetic OneRecord.</small></p>`;layout.parentElement?.appendChild(box)}catch{/* existing OneRecord remains usable if extension is outside scope */}}

async function injectVersion(){try{release=await api('/api/v05/release');let el=document.querySelector<HTMLElement>('.v05-version');if(!el){el=document.createElement('div');el.className='v05-version';document.body.appendChild(el)}el.textContent=`CarePath ${release.version} • ${String(release.gitCommit).slice(0,10)} • ${release.architecture}`;}catch{/* deployment may still be old */}}

async function initialise(){try{const me=await api('/api/auth/me');currentUser=me.user;injectNav();injectVersion();injectRecordExtensions()}catch{currentUser=null}}

const observer=new MutationObserver(()=>{if(currentUser){injectNav();injectRecordExtensions()}});
observer.observe(document.documentElement,{childList:true,subtree:true});
window.addEventListener('carepath:user-changed',()=>initialise());
initialise();
