import express from 'express';
import cors from 'cors';
import helmet from 'helmet';
import session from 'express-session';
import bcrypt from 'bcryptjs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { randomUUID } from 'node:crypto';
import { appointments, bedCapacity, facilities, patients, referrals, auditEvents, users } from './data.js';
import { requireAuth, requireRole } from './auth.js';
import { answerAyanda } from './ayanda.js';
import { getOpenAISettings, testOpenAISettings, updateOpenAISettings } from './aiSettings.js';
import { canTransition, type Appointment, type AppointmentStatus, type BedType, type CareOutcome, type Referral, type ReferralStatus, type Role } from './domain.js';

const app = express();
const port = Number(process.env.PORT || 8080);
const webOrigin = process.env.WEB_ORIGIN || 'http://localhost:5173';
const production = process.env.NODE_ENV === 'production';

app.set('trust proxy', 1);
app.use(helmet({ contentSecurityPolicy: production ? undefined : false }));
app.use(cors({ origin: webOrigin, credentials: true }));
app.use(express.json({ limit: '512kb' }));
app.use(session({
  name: 'carepath.sid',
  secret: process.env.SESSION_SECRET || 'development-only-change-me',
  resave: false,
  saveUninitialized: false,
  cookie: { httpOnly: true, sameSite: 'lax', secure: production, maxAge: 8 * 60 * 60 * 1000 }
}));

const auth = requireAuth(users);
const managementRoles: Role[] = ['ADMIN','MANAGER','AUDITOR'];
const bookingRoles: Role[] = ['ADMIN','CLINICIAN','SPECIALIST','COORDINATOR','PATIENT_NAVIGATOR'];
const medicationWriteRoles: Role[] = ['ADMIN','CLINICIAN','SPECIALIST','PHARMACIST'];
const vaccineWriteRoles: Role[] = ['ADMIN','CLINICIAN','SPECIALIST','NURSE','PHARMACIST'];
const transferWriteRoles: Role[] = ['ADMIN','CLINICIAN','SPECIALIST','NURSE','COORDINATOR','PATIENT_NAVIGATOR'];
const transferManageRoles: Role[] = ['ADMIN','NURSE','COORDINATOR','MANAGER'];
const paramValue = (value: string | string[] | undefined): string => Array.isArray(value) ? (value[0] ?? '') : (value ?? '');
const safeUser = (user: typeof users[number]) => ({ id:user.id, username:user.username, displayName:user.displayName, role:user.role, facilityId:user.facilityId, patientId:user.patientId });
const patientName = (patientId:string) => { const p=patients.find(x=>x.id===patientId); return p ? `${p.firstName} ${p.surname}` : patientId; };
const facilityName = (facilityId:string) => facilities.find(f=>f.id===facilityId)?.name ?? facilityId;
const availableBeds = (facilityId:string, bedType:BedType) => { const c=bedCapacity.find(x=>x.facilityId===facilityId&&x.bedType===bedType); return c ? Math.max(0,c.staffedBeds-c.occupiedBeds-c.reservedBeds) : 0; };
const facilityCapacity = (facilityId:string) => bedCapacity.filter(c=>c.facilityId===facilityId).map(c=>({...c,availableBeds:Math.max(0,c.staffedBeds-c.occupiedBeds-c.reservedBeds)}));
const bedTypeForService = (service:string):BedType|undefined => /surgery|oncology|admission|inpatient/i.test(service) ? 'GENERAL' : undefined;
const nowIso = () => new Date().toISOString();

function ensureExpandedPatients(target=120){
  if(patients.length>=target)return;
  const originals=[...patients];
  const firstNames=['Amahle','Katlego','Lethabo','Zinhle','Lwazi','Tebogo','Anele','Siyabonga','Rethabile','Nthabiseng','Khumo','Lukhanyo','Mpumelelo','Nompumelelo','Onalenna','Tshegofatso','Zola','Minenhle','Keitumetse','Asanda'];
  const surnames=['Mokoena','Nkosi','Molefe','Dlamini','Mabena','Mahlangu','Sithole','Ndlovu','Radebe','Maseko','Motaung','Khumalo','Mofokeng','Modise','Baloyi','Mthembu','Shabangu','Mhlongo','Nkomo','Mabaso'];
  for(let i=patients.length;i<target;i++){
    const base=originals[i%originals.length];
    const n=i+1;
    const suffix=`${n}`;
    patients.push({
      ...base,
      id:`pat-${String(n).padStart(3,'0')}`,
      syntheticId:`SYN-CP-${String(n).padStart(4,'0')}`,
      firstName:firstNames[i%firstNames.length],
      surname:surnames[(i*3)%surnames.length],
      dateOfBirth:`${1958+(i%48)}-${String((i%12)+1).padStart(2,'0')}-${String((i%27)+1).padStart(2,'0')}`,
      phone:`+27 71 500 ${String(n).padStart(4,'0')}`,
      allergies:base.allergies.map((x,j)=>({...x,id:`all-${suffix}-${j+1}`})),
      conditions:base.conditions.map((x,j)=>({...x,id:`cond-${suffix}-${j+1}`})),
      medications:base.medications.map((x,j)=>({...x,id:`med-${suffix}-${j+1}`})),
      results:base.results.map((x,j)=>({...x,id:`res-${suffix}-${j+1}`})),
      encounters:base.encounters.map((x,j)=>({...x,id:`enc-${suffix}-${j+1}`}))
    });
  }
}
ensureExpandedPatients(120);

type NotificationKind='APPOINTMENT'|'REFERRAL'|'CAPACITY'|'MEDICATION'|'VACCINE'|'TRANSFER'|'SYSTEM';
type NotificationPriority='LOW'|'MEDIUM'|'HIGH';
interface CareNotification{ id:string; kind:NotificationKind; priority:NotificationPriority; title:string; message:string; createdAt:string; patientId?:string; facilityId?:string; recipientUserId?:string; roles?:Role[]; actionView?:string; readBy:string[]; }
interface VaccineRecord{ id:string; patientId:string; vaccine:string; dose:string; administeredAt:string; administeredFacility:string; nextDueAt?:string; status:'COMPLETE'|'DUE'|'OVERDUE'; synthetic:true; }
type AmbulanceType='BASIC'|'ADVANCED'|'ICU'|'NEONATAL';
type AmbulanceStatus='AVAILABLE'|'DISPATCHED'|'MAINTENANCE';
interface Ambulance{ id:string; callSign:string; type:AmbulanceType; status:AmbulanceStatus; stationFacilityId:string; crew:string; capabilities:string[]; etaMinutes:number; updatedAt:string; synthetic:true; }
type TransferPriority='ROUTINE'|'URGENT'|'EMERGENCY';
type TransferStatus='REQUESTED'|'ASSIGNED'|'EN_ROUTE'|'PATIENT_ON_BOARD'|'ARRIVED'|'COMPLETED'|'CANCELLED';
interface TransferRequest{ id:string; patientId:string; referralId?:string; pickupFacilityId:string; destinationFacilityId:string; ambulanceId?:string; priority:TransferPriority; requiredLevel:AmbulanceType; scheduledAt:string; status:TransferStatus; requestedBy:string; note?:string; createdAt:string; updatedAt:string; synthetic:true; }

const vaccinations:VaccineRecord[]=[];
const vaccineNames=['Influenza','COVID-19 booster','Tetanus','Hepatitis B','Pneumococcal'];
for(let i=0;i<patients.length;i++){
  if(i%2!==0)continue;
  const p=patients[i];
  const daysOffset=(i%5===0?-20:i%5===1?14:120);
  const next=new Date(Date.now()+daysOffset*86400000);
  vaccinations.push({id:`vax-${i+1}-1`,patientId:p.id,vaccine:vaccineNames[i%vaccineNames.length],dose:i%3===0?'Booster':'Dose 1',administeredAt:new Date(Date.now()-(120+i%180)*86400000).toISOString(),administeredFacility:i%2===0?'Mahlasedi Community Clinic (Demo)':'Ubuntu Community Health Centre (Demo)',nextDueAt:next.toISOString(),status:daysOffset<0?'OVERDUE':daysOffset<=30?'DUE':'COMPLETE',synthetic:true});
}

const ambulances:Ambulance[]=[
  {id:'amb-001',callSign:'GP-EMS-01',type:'ADVANCED',status:'AVAILABLE',stationFacilityId:'fac-hosp-2',crew:'ALS crew A',capabilities:['BLS','ALS','Oxygen','ECG'],etaMinutes:12,updatedAt:nowIso(),synthetic:true},
  {id:'amb-002',callSign:'GP-EMS-02',type:'BASIC',status:'AVAILABLE',stationFacilityId:'fac-clinic-2',crew:'BLS crew B',capabilities:['BLS','Oxygen'],etaMinutes:9,updatedAt:nowIso(),synthetic:true},
  {id:'amb-003',callSign:'GP-ICU-03',type:'ICU',status:'AVAILABLE',stationFacilityId:'fac-hosp-1',crew:'Critical care crew C',capabilities:['ALS','Ventilator','Monitor','Infusion pump'],etaMinutes:18,updatedAt:nowIso(),synthetic:true},
  {id:'amb-004',callSign:'GP-EMS-04',type:'ADVANCED',status:'DISPATCHED',stationFacilityId:'fac-hosp-3',crew:'ALS crew D',capabilities:['BLS','ALS','Oxygen','ECG'],etaMinutes:22,updatedAt:nowIso(),synthetic:true},
  {id:'amb-005',callSign:'GP-EMS-05',type:'BASIC',status:'AVAILABLE',stationFacilityId:'fac-hosp-5',crew:'BLS crew E',capabilities:['BLS','Oxygen'],etaMinutes:15,updatedAt:nowIso(),synthetic:true},
  {id:'amb-006',callSign:'LP-EMS-06',type:'ADVANCED',status:'AVAILABLE',stationFacilityId:'fac-clinic-1',crew:'ALS crew F',capabilities:['BLS','ALS','Oxygen','ECG'],etaMinutes:11,updatedAt:nowIso(),synthetic:true},
  {id:'amb-007',callSign:'LP-ICU-07',type:'ICU',status:'AVAILABLE',stationFacilityId:'fac-hosp-4',crew:'Critical care crew G',capabilities:['ALS','Ventilator','Monitor','Infusion pump'],etaMinutes:20,updatedAt:nowIso(),synthetic:true},
  {id:'amb-008',callSign:'GP-NEO-08',type:'NEONATAL',status:'AVAILABLE',stationFacilityId:'fac-hosp-2',crew:'Neonatal transfer crew',capabilities:['Neonatal incubator','Ventilator','Monitor'],etaMinutes:25,updatedAt:nowIso(),synthetic:true},
  {id:'amb-009',callSign:'GP-EMS-09',type:'BASIC',status:'MAINTENANCE',stationFacilityId:'fac-hosp-3',crew:'BLS crew H',capabilities:['BLS','Oxygen'],etaMinutes:0,updatedAt:nowIso(),synthetic:true},
  {id:'amb-010',callSign:'GP-EMS-10',type:'ADVANCED',status:'AVAILABLE',stationFacilityId:'fac-hosp-5',crew:'ALS crew I',capabilities:['BLS','ALS','Oxygen','ECG'],etaMinutes:16,updatedAt:nowIso(),synthetic:true},
  {id:'amb-011',callSign:'LP-EMS-11',type:'BASIC',status:'AVAILABLE',stationFacilityId:'fac-hosp-4',crew:'BLS crew J',capabilities:['BLS','Oxygen'],etaMinutes:13,updatedAt:nowIso(),synthetic:true},
  {id:'amb-012',callSign:'GP-ICU-12',type:'ICU',status:'AVAILABLE',stationFacilityId:'fac-hosp-2',crew:'Critical care crew K',capabilities:['ALS','Ventilator','Monitor','Infusion pump'],etaMinutes:14,updatedAt:nowIso(),synthetic:true}
];

const transfers:TransferRequest[]=[
  {id:'trn-3001',patientId:patients[3].id,referralId:referrals[3]?.id,pickupFacilityId:'fac-clinic-2',destinationFacilityId:'fac-hosp-3',ambulanceId:'amb-004',priority:'URGENT',requiredLevel:'ADVANCED',scheduledAt:new Date(Date.now()+45*60000).toISOString(),status:'EN_ROUTE',requestedBy:'Care Coordinator',note:'Synthetic inter-facility specialist transfer',createdAt:new Date(Date.now()-30*60000).toISOString(),updatedAt:nowIso(),synthetic:true},
  {id:'trn-3002',patientId:patients[8].id,referralId:referrals[8]?.id,pickupFacilityId:'fac-clinic-1',destinationFacilityId:'fac-hosp-4',priority:'ROUTINE',requiredLevel:'BASIC',scheduledAt:new Date(Date.now()+3*3600000).toISOString(),status:'REQUESTED',requestedBy:'Patient Navigator',note:'Synthetic scheduled transfer request',createdAt:new Date(Date.now()-20*60000).toISOString(),updatedAt:nowIso(),synthetic:true}
];

const notifications:CareNotification[]=[];
function addNotification(input:Omit<CareNotification,'id'|'createdAt'|'readBy'>){notifications.unshift({id:randomUUID(),createdAt:nowIso(),readBy:[],...input})}
function seedNotifications(){
  if(notifications.length)return;
  appointments.slice(0,8).forEach((a,i)=>addNotification({kind:'APPOINTMENT',priority:i%3===0?'HIGH':'MEDIUM',title:'Appointment reminder',message:`${patientName(a.patientId)} has a ${a.service} appointment at ${facilityName(a.facilityId)}.`,patientId:a.patientId,facilityId:a.facilityId,actionView:'appointments'}));
  referrals.filter(r=>['SUBMITTED','RECEIVED','INFO_REQUESTED'].includes(r.status)).slice(0,6).forEach(r=>addNotification({kind:'REFERRAL',priority:'HIGH',title:'Referral requires attention',message:`${patientName(r.patientId)} — ${r.service} referral is ${r.status.toLowerCase().replace('_',' ')}.`,patientId:r.patientId,facilityId:r.destinationFacilityId,roles:['COORDINATOR','SPECIALIST','MANAGER','ADMIN'],actionView:'referrals'}));
  vaccinations.filter(v=>v.status!=='COMPLETE').slice(0,8).forEach(v=>addNotification({kind:'VACCINE',priority:v.status==='OVERDUE'?'HIGH':'MEDIUM',title:v.status==='OVERDUE'?'Vaccination overdue':'Vaccination due soon',message:`${patientName(v.patientId)} — ${v.vaccine} ${v.dose}.`,patientId:v.patientId,roles:['CLINICIAN','NURSE','PHARMACIST','PATIENT_NAVIGATOR'],actionView:'medication'}));
  bedCapacity.filter(c=>availableBeds(c.facilityId,c.bedType)<=1).slice(0,5).forEach(c=>addNotification({kind:'CAPACITY',priority:'HIGH',title:'Bed capacity constrained',message:`${facilityName(c.facilityId)} has ${availableBeds(c.facilityId,c.bedType)} ${c.bedType.toLowerCase().replace('_',' ')} beds available in the synthetic feed.`,facilityId:c.facilityId,roles:['COORDINATOR','MANAGER','ADMIN','NURSE'],actionView:'facilities'}));
  transfers.forEach(t=>addNotification({kind:'TRANSFER',priority:t.priority==='EMERGENCY'?'HIGH':'MEDIUM',title:'Patient transfer update',message:`${patientName(t.patientId)} transfer is ${t.status.toLowerCase().replaceAll('_',' ')}.`,patientId:t.patientId,facilityId:t.destinationFacilityId,roles:['COORDINATOR','NURSE','PATIENT_NAVIGATOR','MANAGER'],actionView:'transfers'}));
}
seedNotifications();

function visibleReferralsFor(user: typeof users[number]) {
  if (managementRoles.includes(user.role)) return referrals;
  if (user.role === 'PATIENT') return referrals.filter(r=>r.patientId===user.patientId);
  if (!user.facilityId) return [];
  return referrals.filter(r=>r.sourceFacilityId===user.facilityId||r.destinationFacilityId===user.facilityId);
}

function visiblePatientIdsFor(user: typeof users[number]):Set<string> {
  if (managementRoles.includes(user.role)) return new Set(patients.map(p=>p.id));
  if (user.role === 'PATIENT') return new Set(user.patientId?[user.patientId]:[]);
  const ids=new Set(visibleReferralsFor(user).map(r=>r.patientId));
  const ownFacility=user.facilityId?facilityName(user.facilityId):'';
  if(ownFacility){for(const p of patients){const items=[...p.allergies,...p.conditions,...p.medications,...p.results,...p.encounters];if(items.some(i=>i.sourceFacility===ownFacility))ids.add(p.id)}}
  return ids;
}
function canReadPatient(user: typeof users[number], patientId:string){return Boolean(patientId)&&visiblePatientIdsFor(user).has(patientId)}
function visibleAppointmentsFor(user: typeof users[number]) {
  if (managementRoles.includes(user.role)) return appointments;
  if (user.role==='PATIENT') return appointments.filter(a=>a.patientId===user.patientId);
  const referralIds=new Set(visibleReferralsFor(user).map(r=>r.id));
  return appointments.filter(a=>a.facilityId===user.facilityId||(a.referralId&&referralIds.has(a.referralId)));
}
function visibleTransfersFor(user: typeof users[number]){
  if(managementRoles.includes(user.role))return transfers;
  if(user.role==='PATIENT')return transfers.filter(t=>t.patientId===user.patientId);
  if(!user.facilityId)return [];
  return transfers.filter(t=>t.pickupFacilityId===user.facilityId||t.destinationFacilityId===user.facilityId||canReadPatient(user,t.patientId));
}
function visibleNotificationsFor(user: typeof users[number]){
  if(managementRoles.includes(user.role))return notifications;
  return notifications.filter(n=>n.recipientUserId===user.id||(user.role==='PATIENT'&&n.patientId===user.patientId)||(Boolean(user.facilityId)&&n.facilityId===user.facilityId)||(n.roles?.includes(user.role)));
}

function roleCanTransition(role:Role,to:ReferralStatus){
  if(role==='ADMIN')return true;
  if(role==='CLINICIAN')return ['SUBMITTED','CANCELLED'].includes(to);
  if(role==='COORDINATOR'||role==='SPECIALIST')return ['RECEIVED','INFO_REQUESTED','ACCEPTED','DECLINED','REDIRECTED','SCHEDULED','PATIENT_NOTIFIED','ATTENDED','MISSED','FEEDBACK_PENDING','FOLLOWUP_REQUIRED','CLOSED'].includes(to);
  if(role==='NURSE')return ['PATIENT_NOTIFIED','ATTENDED','MISSED','FOLLOWUP_REQUIRED'].includes(to);
  if(role==='PATIENT_NAVIGATOR')return ['PATIENT_NOTIFIED','FOLLOWUP_REQUIRED','SCHEDULED'].includes(to);
  if(role==='MANAGER')return ['REOPENED'].includes(to);
  return false;
}

function logAudit(actor:string,action:string,objectType:string,objectId:string,source:'UI'|'VOICE'|'AI'|'SYSTEM',outcome:'SUCCESS'|'DENIED'='SUCCESS',reason?:string){auditEvents.unshift({id:randomUUID(),at:nowIso(),actor,action,objectType,objectId,source,outcome,reason})}
function referralView(r:Referral){return {...r,patientName:patientName(r.patientId),sourceFacilityName:facilityName(r.sourceFacilityId),destinationFacilityName:facilityName(r.destinationFacilityId),bedAvailability:r.requiresBed&&r.bedType?{bedType:r.bedType,available:availableBeds(r.destinationFacilityId,r.bedType)}:null}}
function appointmentView(a:Appointment){return {...a,patientName:patientName(a.patientId),facilityName:facilityName(a.facilityId),referral:a.referralId?referrals.find(r=>r.id===a.referralId):undefined,bedAvailability:a.requiresBed&&a.bedType?availableBeds(a.facilityId,a.bedType):null}}
function transferView(t:TransferRequest){const ambulance=t.ambulanceId?ambulances.find(a=>a.id===t.ambulanceId):undefined;return {...t,patientName:patientName(t.patientId),pickupFacilityName:facilityName(t.pickupFacilityId),destinationFacilityName:facilityName(t.destinationFacilityId),ambulance:ambulance?{...ambulance,stationName:facilityName(ambulance.stationFacilityId)}:null}}
function ambulanceView(a:Ambulance){const activeTransfer=transfers.find(t=>t.ambulanceId===a.id&&!['COMPLETED','CANCELLED'].includes(t.status));return {...a,stationName:facilityName(a.stationFacilityId),activeTransfer:activeTransfer?{id:activeTransfer.id,patientName:patientName(activeTransfer.patientId),status:activeTransfer.status,destinationFacilityName:facilityName(activeTransfer.destinationFacilityId)}:null}}
function alternativesFor(service:string,bedType:BedType){return facilities.filter(f=>(f.type==='PUBLIC'||f.type==='PRIVATE')&&f.services.some(s=>s.toLowerCase().includes(service.toLowerCase().split(' ')[0]))&&availableBeds(f.id,bedType)>0).map(f=>({facilityId:f.id,facilityName:f.name,availableBeds:availableBeds(f.id,bedType),bedType}))}
function reserveBed(facilityId:string,bedType:BedType){const c=bedCapacity.find(x=>x.facilityId===facilityId&&x.bedType===bedType);if(!c||availableBeds(facilityId,bedType)<1)return false;c.reservedBeds+=1;c.updatedAt=nowIso();return true}
function releaseReservedBed(facilityId:string,bedType?:BedType){if(!bedType)return;const c=bedCapacity.find(x=>x.facilityId===facilityId&&x.bedType===bedType);if(c&&c.reservedBeds>0){c.reservedBeds-=1;c.updatedAt=nowIso()}}
function checkInBed(facilityId:string,bedType?:BedType){if(!bedType)return;const c=bedCapacity.find(x=>x.facilityId===facilityId&&x.bedType===bedType);if(c){if(c.reservedBeds>0)c.reservedBeds-=1;c.occupiedBeds=Math.min(c.staffedBeds,c.occupiedBeds+1);c.updatedAt=nowIso()}}
function dischargeBed(facilityId:string,bedType?:BedType){if(!bedType)return;const c=bedCapacity.find(x=>x.facilityId===facilityId&&x.bedType===bedType);if(c&&c.occupiedBeds>0){c.occupiedBeds-=1;c.updatedAt=nowIso()}}

function ambulanceCanServe(a:Ambulance,required:AmbulanceType){if(a.status!=='AVAILABLE')return false;if(required==='BASIC')return true;if(required==='ADVANCED')return ['ADVANCED','ICU','NEONATAL'].includes(a.type);if(required==='ICU')return a.type==='ICU';return a.type==='NEONATAL'}
function findAmbulance(required:AmbulanceType){return ambulances.filter(a=>ambulanceCanServe(a,required)).sort((a,b)=>a.etaMinutes-b.etaMinutes)[0]}
function assignAmbulance(transfer:TransferRequest,ambulance:Ambulance){transfer.ambulanceId=ambulance.id;transfer.status='ASSIGNED';transfer.updatedAt=nowIso();ambulance.status='DISPATCHED';ambulance.updatedAt=transfer.updatedAt}
function releaseAmbulance(ambulanceId?:string){if(!ambulanceId)return;const ambulance=ambulances.find(a=>a.id===ambulanceId);if(ambulance&&ambulance.status==='DISPATCHED'){ambulance.status='AVAILABLE';ambulance.updatedAt=nowIso()}}

function outcomeSummary(source:Referral[]){const hospitalFacilities=facilities.filter(f=>f.type==='PUBLIC'||f.type==='PRIVATE');return hospitalFacilities.map(f=>{const referred=source.filter(r=>r.destinationFacilityId===f.id);const withOutcome=referred.filter(r=>r.outcome&&r.outcome!=='UNKNOWN');const count=(outcome:CareOutcome)=>withOutcome.filter(r=>r.outcome===outcome).length;const recovered=count('RECOVERED'),improved=count('IMPROVED'),deceased=count('DECEASED'),ongoing=count('ONGOING'),favourable=recovered+improved,resolved=favourable+deceased;const acknowledged=referred.filter(r=>r.acknowledgedAt);const medianAckHours=acknowledged.length?Math.round(acknowledged.map(r=>Math.max(0,(Date.parse(r.acknowledgedAt!)-Date.parse(r.createdAt))/3600000)).sort((a,b)=>a-b)[Math.floor(acknowledged.length/2)]*10)/10:null;return{facilityId:f.id,facilityName:f.name,type:f.type,province:f.province,referred:referred.length,outcomesRecorded:withOutcome.length,recovered,improved,deceased,ongoing,unknown:referred.length-withOutcome.length,favourableObservedPct:resolved?Math.round(favourable/resolved*100):null,medianAckHours}}).filter(x=>x.referred>0).sort((a,b)=>(b.favourableObservedPct??-1)-(a.favourableObservedPct??-1))}

function accessProfile(role:Role){const matrix:Record<Role,string[]>={ADMIN:['All synthetic records','User/role administration','OpenAI API settings','Appointment Management Centre','Notifications','Medication & Vaccine Management','Ambulance and transfer management','Bed capacity','Audit','All referral actions','Outcome analytics'],CLINICIAN:['Scoped patient records','Create/submit referrals','Book appointments','Medication management','Vaccination management','Request patient transfer','Check destination capacity','Ayanda governed actions','Care gaps','Notifications'],SPECIALIST:['Receiving-facility patients','Accept/coordinate referrals','Appointment management','Medication management','Vaccination management','Request patient transfer','Record outcomes','Bed capacity','Care gaps'],NURSE:['Receiving-facility patient context','Check-in/follow-up updates','Vaccination management','Ambulance transfer workflow','Bed capacity','Patient navigation','Notifications'],COORDINATOR:['Receiving/referring queues','Appointment scheduling','Ambulance dispatch','Bed-capacity checks','Referral transitions','Record outcomes','Notifications'],PHARMACIST:['Scoped medication context','Medication reconciliation','Vaccination records','Patient record provenance','Notifications'],LAB_TECH:['Scoped result context','Diagnostic-result provenance'],PATIENT_NAVIGATOR:['Scoped referrals','Appointment booking','Transfer requests','Follow-up','Patient communication workflow','Notifications'],MANAGER:['All synthetic operational data','Capacity analytics','Ambulance availability','Transfer analytics','Outcome analytics','Command Centre','Audit','Notifications'],AUDITOR:['Read-only records','Audit/provenance','Access-event review','Read-only transfer and notification context'],PATIENT:['Own synthetic OneRecord','Own referrals','Own appointments','Own medications/vaccines','Own transfer status','Own notifications','Own Health Passport']};return matrix[role]}

app.get('/api/health',(_req,res)=>res.json({ok:true,service:'carepath-api',version:'0.4.0',syntheticData:true,patients:patients.length}));
app.post('/api/auth/login',async(req,res)=>{const username=String(req.body?.username||'').trim().toLowerCase(),password=String(req.body?.password||'');const user=users.find(u=>u.username===username);if(!user||!(await bcrypt.compare(password,user.passwordHash)))return res.status(401).json({error:'Invalid demo credentials'});req.session.userId=user.id;logAudit(user.displayName,'auth.login','User',user.id,'UI');res.json({user:safeUser(user),syntheticData:true})});
app.post('/api/auth/logout',auth,(req,res)=>{const actor=req.currentUser!.displayName,userId=req.currentUser!.id;req.session.destroy(()=>{logAudit(actor,'auth.logout','User',userId,'UI');res.json({ok:true})})});
app.get('/api/auth/me',auth,(req,res)=>res.json({user:safeUser(req.currentUser!),syntheticData:true,access:accessProfile(req.currentUser!.role)}));
app.post('/api/auth/switch-demo',auth,(req,res)=>{const username=String(req.body?.username||'').trim().toLowerCase(),next=users.find(u=>u.username===username);if(!next)return res.status(404).json({error:'Demo user type not found'});const actor=req.currentUser!.displayName;req.session.userId=next.id;logAudit(actor,'auth.demo_role_switch','User',next.id,'UI','SUCCESS',`Switched demo context to ${next.role}`);res.json({user:safeUser(next),access:accessProfile(next.role),demoOnly:true})});
app.get('/api/demo/users',auth,(_req,res)=>res.json({users:users.map(safeUser),demoOnly:true}));
app.get('/api/access/profile',auth,(req,res)=>res.json({role:req.currentUser!.role,access:accessProfile(req.currentUser!.role)}));

app.get('/api/dashboard',auth,(req,res)=>{const scoped=visibleReferralsFor(req.currentUser!),stale=scoped.filter(r=>['SUBMITTED','RECEIVED','INFO_REQUESTED'].includes(r.status)&&Date.now()-Date.parse(r.updatedAt)>24*3600000),scheduled=scoped.filter(r=>r.status==='SCHEDULED'||r.status==='PATIENT_NOTIFIED'),visiblePatients=patients.filter(p=>canReadPatient(req.currentUser!,p.id)),outcomes=scoped.filter(r=>r.outcome&&r.outcome!=='UNKNOWN'),visibleAppointments=visibleAppointmentsFor(req.currentUser!),beds=bedCapacity.reduce((n,c)=>n+Math.max(0,c.staffedBeds-c.occupiedBeds-c.reservedBeds),0),visibleNotifications=visibleNotificationsFor(req.currentUser!),visibleTransfers=visibleTransfersFor(req.currentUser!),visibleVax=vaccinations.filter(v=>canReadPatient(req.currentUser!,v.patientId));res.json({syntheticData:true,metrics:{patients:visiblePatients.length,totalSyntheticPatients:patients.length,openReferrals:scoped.filter(r=>!['CLOSED','CANCELLED','DECLINED'].includes(r.status)).length,awaitingAcceptance:scoped.filter(r=>['SUBMITTED','RECEIVED','INFO_REQUESTED'].includes(r.status)).length,scheduled:scheduled.length,stale:stale.length,facilities:facilities.length,outcomesRecorded:outcomes.length,recoveredOrImproved:outcomes.filter(r=>['RECOVERED','IMPROVED'].includes(r.outcome!)).length,deceased:outcomes.filter(r=>r.outcome==='DECEASED').length,appointments:visibleAppointments.filter(a=>!['CANCELLED','COMPLETED','NO_SHOW'].includes(a.status)).length,availableBeds:beds,unreadNotifications:visibleNotifications.filter(n=>!n.readBy.includes(req.currentUser!.id)).length,availableAmbulances:ambulances.filter(a=>a.status==='AVAILABLE').length,activeTransfers:visibleTransfers.filter(t=>!['COMPLETED','CANCELLED'].includes(t.status)).length,vaccinesDue:visibleVax.filter(v=>['DUE','OVERDUE'].includes(v.status)).length},staleReferrals:stale.slice(0,8).map(referralView),recentAudit:auditEvents.slice(0,7),outcomeSnapshot:outcomeSummary(scoped).slice(0,5),recentNotifications:visibleNotifications.slice(0,5).map(n=>({...n,read:n.readBy.includes(req.currentUser!.id)})),activeTransfers:visibleTransfers.filter(t=>!['COMPLETED','CANCELLED'].includes(t.status)).slice(0,5).map(transferView)})});

app.get('/api/patients',auth,(req,res)=>{const list=patients.filter(p=>canReadPatient(req.currentUser!,p.id)),q=String(req.query.q||'').trim().toLowerCase(),filtered=q?list.filter(p=>`${p.firstName} ${p.surname} ${p.syntheticId}`.toLowerCase().includes(q)):list;res.json({syntheticData:true,totalSyntheticPatients:patients.length,patients:filtered.map(p=>({...p,allergies:p.allergies.length,conditions:p.conditions.length,medications:p.medications.length,results:p.results.length,encounters:p.encounters.length,vaccinations:vaccinations.filter(v=>v.patientId===p.id).length}))})});
app.get('/api/patients/:id',auth,(req,res)=>{const patientId=paramValue(req.params.id),patient=patients.find(p=>p.id===patientId);if(!patient)return res.status(404).json({error:'Patient not found'});if(!canReadPatient(req.currentUser!,patient.id)){logAudit(req.currentUser!.displayName,'patient.read','Patient',patient.id,'UI','DENIED','Role/facility scope');return res.status(403).json({error:'Not authorised for this patient'})}logAudit(req.currentUser!.displayName,'patient.read','Patient',patient.id,'UI');const patientReferrals=referrals.filter(r=>r.patientId===patient.id&&visibleReferralsFor(req.currentUser!).some(v=>v.id===r.id)).map(referralView);const patientAppointments=visibleAppointmentsFor(req.currentUser!).filter(a=>a.patientId===patient.id).map(appointmentView);res.json({patient,referrals:patientReferrals,appointments:patientAppointments,vaccinations:vaccinations.filter(v=>v.patientId===patient.id),transfers:visibleTransfersFor(req.currentUser!).filter(t=>t.patientId===patient.id).map(transferView)})});

function passportResponse(req:any,res:any,requestedId?:string){const requested=requestedId||req.currentUser!.patientId||visiblePatientIdsFor(req.currentUser!)[Symbol.iterator]().next().value;if(!requested||!canReadPatient(req.currentUser!,requested))return res.status(403).json({error:'No authorised Health Passport patient available'});const patient=patients.find(p=>p.id===requested);if(!patient)return res.status(404).json({error:'Patient not found'});res.json({patient,referrals:referrals.filter(r=>r.patientId===patient.id&&visibleReferralsFor(req.currentUser!).some((v:Referral)=>v.id===r.id)).map(referralView),appointments:visibleAppointmentsFor(req.currentUser!).filter((a:Appointment)=>a.patientId===patient.id).map(appointmentView),vaccinations:vaccinations.filter(v=>v.patientId===patient.id),transfers:visibleTransfersFor(req.currentUser!).filter(t=>t.patientId===patient.id).map(transferView),notifications:visibleNotificationsFor(req.currentUser!).filter(n=>n.patientId===patient.id).slice(0,10),accessNotice:'Synthetic demo Health Passport. Sharing and consent controls are illustrative.'})}
app.get('/api/passport',auth,(req,res)=>passportResponse(req,res));
app.get('/api/passport/:id',auth,(req,res)=>passportResponse(req,res,paramValue(req.params.id)));
app.post('/api/passport/:id/share',auth,(req,res)=>{const patientId=paramValue(req.params.id);if(!canReadPatient(req.currentUser!,patientId))return res.status(403).json({error:'Not authorised for this patient'});if(!['PATIENT','ADMIN'].includes(req.currentUser!.role))return res.status(403).json({error:'Patient-directed sharing is limited to the patient or administrator in this demo'});const token=`DEMO-${randomUUID().slice(0,8).toUpperCase()}`,expiresAt=new Date(Date.now()+15*60*1000).toISOString();logAudit(req.currentUser!.displayName,'passport.share.create','Patient',patientId,'UI');res.json({token,expiresAt,demoOnly:true,message:'Synthetic one-time share code created for demonstration. No live external sharing occurs.'})});

app.get('/api/capacity',auth,(req,res)=>{const facilityId=String(req.query.facilityId||'');const list=facilityId?facilities.filter(f=>f.id===facilityId):facilities.filter(f=>f.type==='PUBLIC'||f.type==='PRIVATE');res.json({syntheticData:true,disclaimer:'Synthetic bed-capacity data for hackathon demonstration only; not a live hospital operations feed.',facilities:list.map(f=>({facilityId:f.id,facilityName:f.name,type:f.type,capacity:facilityCapacity(f.id),totalAvailable:facilityCapacity(f.id).reduce((n,c)=>n+c.availableBeds,0)}))})});
app.get('/api/facilities',auth,(_req,res)=>res.json({facilities:facilities.map(f=>({...f,capacity:facilityCapacity(f.id),totalAvailableBeds:facilityCapacity(f.id).reduce((n,c)=>n+c.availableBeds,0)}))}));

app.get('/api/referrals',auth,(req,res)=>{const staleOnly=req.query.filter==='stale';let list=visibleReferralsFor(req.currentUser!);if(staleOnly)list=list.filter(r=>['SUBMITTED','RECEIVED','INFO_REQUESTED'].includes(r.status)&&Date.now()-Date.parse(r.updatedAt)>24*3600000);res.json({referrals:list.map(referralView)})});
app.post('/api/referrals',auth,requireRole('CLINICIAN','ADMIN'),(req,res)=>{const{patientId,service,reason,destinationFacilityId,priority='ROUTINE',requiresBed}=req.body||{};if(!patients.some(p=>p.id===patientId)||!canReadPatient(req.currentUser!,patientId))return res.status(400).json({error:'Invalid or unauthorised patient'});if(!facilities.some(f=>f.id===destinationFacilityId))return res.status(400).json({error:'Invalid destination facility'});if(!service||!reason)return res.status(400).json({error:'Service and reason are required'});const bedType:BedType|undefined=(requiresBed===true?String(req.body?.bedType||'GENERAL') as BedType:bedTypeForService(String(service)));if(bedType&&availableBeds(destinationFacilityId,bedType)<1)return res.status(409).json({error:`No synthetic ${bedType.toLowerCase().replace('_',' ')} bed is currently available at ${facilityName(destinationFacilityId)}`,alternatives:alternativesFor(String(service),bedType)});const referral:Referral={id:`ref-${Date.now()}`,patientId,service:String(service).slice(0,120),reason:String(reason).slice(0,600),sourceFacilityId:req.currentUser!.facilityId||'fac-clinic-1',destinationFacilityId,owner:req.currentUser!.displayName,status:'DRAFT',priority:priority==='PRIORITY'?'PRIORITY':'ROUTINE',createdAt:nowIso(),updatedAt:nowIso(),requiresBed:Boolean(bedType),bedType,events:[{id:randomUUID(),at:nowIso(),actor:req.currentUser!.displayName,to:'DRAFT',note:'Referral draft created after destination capacity check',source:'UI'}]};referrals.unshift(referral);addNotification({kind:'REFERRAL',priority:'MEDIUM',title:'Referral draft created',message:`${patientName(patientId)} — ${service} referral draft created for ${facilityName(destinationFacilityId)}.`,patientId,facilityId:destinationFacilityId,roles:['COORDINATOR','SPECIALIST'],actionView:'referrals'});logAudit(req.currentUser!.displayName,'referral.create_draft','Referral',referral.id,'UI');res.status(201).json({referral:referralView(referral)})});
app.post('/api/referrals/:id/transition',auth,(req,res)=>{const referralId=paramValue(req.params.id),referral=referrals.find(r=>r.id===referralId);if(!referral)return res.status(404).json({error:'Referral not found'});const to=String(req.body?.to||'') as ReferralStatus;if(!roleCanTransition(req.currentUser!.role,to)){logAudit(req.currentUser!.displayName,'referral.transition','Referral',referral.id,'UI','DENIED',`Role ${req.currentUser!.role} cannot transition to ${to}`);return res.status(403).json({error:'Role is not authorised for this transition'})}if(!visibleReferralsFor(req.currentUser!).some(r=>r.id===referral.id))return res.status(403).json({error:'Referral outside authorised facility scope'});if(!canTransition(referral.status,to))return res.status(409).json({error:`Invalid transition from ${referral.status} to ${to}`});const from=referral.status;referral.status=to;referral.updatedAt=nowIso();if(to==='RECEIVED'&&!referral.acknowledgedAt)referral.acknowledgedAt=referral.updatedAt;referral.events.unshift({id:randomUUID(),at:referral.updatedAt,actor:req.currentUser!.displayName,from,to,note:String(req.body?.note||`Status changed to ${to}`).slice(0,400),source:'UI'});addNotification({kind:'REFERRAL',priority:['MISSED','FOLLOWUP_REQUIRED','INFO_REQUESTED'].includes(to)?'HIGH':'MEDIUM',title:'Referral status updated',message:`${patientName(referral.patientId)} — ${referral.service} is now ${to.toLowerCase().replaceAll('_',' ')}.`,patientId:referral.patientId,facilityId:referral.destinationFacilityId,actionView:'referrals'});logAudit(req.currentUser!.displayName,`referral.${to.toLowerCase()}`,'Referral',referral.id,'UI');res.json({referral:referralView(referral)})});
app.post('/api/referrals/:id/outcome',auth,requireRole('SPECIALIST','COORDINATOR','MANAGER','ADMIN'),(req,res)=>{const referralId=paramValue(req.params.id),referral=referrals.find(r=>r.id===referralId);if(!referral||!visibleReferralsFor(req.currentUser!).some(r=>r.id===referral.id))return res.status(404).json({error:'Referral not found in authorised scope'});const allowed:CareOutcome[]=['RECOVERED','IMPROVED','ONGOING','DECEASED','UNKNOWN'],outcome=String(req.body?.outcome||'') as CareOutcome;if(!allowed.includes(outcome))return res.status(400).json({error:'Invalid outcome'});referral.outcome=outcome;referral.outcomeAt=nowIso();referral.outcomeNote=String(req.body?.note||`Synthetic outcome recorded: ${outcome}`).slice(0,500);referral.updatedAt=referral.outcomeAt;logAudit(req.currentUser!.displayName,'referral.outcome.record','Referral',referral.id,'UI');res.json({referral:referralView(referral)})});

app.get('/api/appointments',auth,(req,res)=>{let list=visibleAppointmentsFor(req.currentUser!);if(req.query.upcoming==='true')list=list.filter(a=>Date.parse(a.startAt)>=Date.now()&&!['CANCELLED','COMPLETED','NO_SHOW'].includes(a.status));res.json({syntheticData:true,appointments:list.sort((a,b)=>Date.parse(a.startAt)-Date.parse(b.startAt)).map(appointmentView)})});
app.post('/api/appointments',auth,requireRole(...bookingRoles),(req,res)=>{const patientId=String(req.body?.patientId||''),facilityId=String(req.body?.facilityId||''),service=String(req.body?.service||'').trim(),startAt=String(req.body?.startAt||''),referralId=req.body?.referralId?String(req.body.referralId):undefined,durationMinutes=Math.min(240,Math.max(15,Number(req.body?.durationMinutes||30)));if(!patientId||!facilityId||!service||!startAt)return res.status(400).json({error:'Patient, facility, service and appointment time are required'});if(!canReadPatient(req.currentUser!,patientId))return res.status(403).json({error:'Patient is outside authorised scope'});if(!facilities.some(f=>f.id===facilityId))return res.status(400).json({error:'Invalid facility'});if(!Number.isFinite(Date.parse(startAt))||Date.parse(startAt)<Date.now()-5*60*1000)return res.status(400).json({error:'Appointment must have a valid current or future time'});const referral=referralId?referrals.find(r=>r.id===referralId):undefined;if(referralId&&!referral)return res.status(404).json({error:'Referral not found'});const bedType:BedType|undefined=referral?.bedType||(req.body?.requiresBed===true?String(req.body?.bedType||'GENERAL') as BedType:bedTypeForService(service));if(bedType&&!reserveBed(facilityId,bedType))return res.status(409).json({error:`No synthetic ${bedType.toLowerCase().replace('_',' ')} bed is available at ${facilityName(facilityId)} for this booking`,alternatives:alternativesFor(service,bedType)});const appt:Appointment={id:`appt-${Date.now()}`,patientId,facilityId,referralId,service,startAt:new Date(startAt).toISOString(),durationMinutes,status:'BOOKED',bookedBy:req.currentUser!.displayName,bookingSource:'UI',requiresBed:Boolean(bedType),bedType,note:String(req.body?.note||'').slice(0,400)||undefined,createdAt:nowIso(),updatedAt:nowIso()};appointments.push(appt);if(referral){referral.appointmentAt=appt.startAt;if(referral.status==='ACCEPTED')referral.status='SCHEDULED';referral.updatedAt=appt.updatedAt;referral.events.unshift({id:randomUUID(),at:appt.updatedAt,actor:req.currentUser!.displayName,from:'ACCEPTED',to:referral.status,note:`Appointment booked for ${appt.startAt}`,source:'UI'})}addNotification({kind:'APPOINTMENT',priority:'MEDIUM',title:'Appointment booked',message:`${patientName(patientId)} — ${service} at ${facilityName(facilityId)} on ${new Date(appt.startAt).toLocaleString('en-ZA')}.`,patientId,facilityId,actionView:'appointments'});logAudit(req.currentUser!.displayName,'appointment.book','Appointment',appt.id,'UI');res.status(201).json({appointment:appointmentView(appt)})});
app.post('/api/referrals/:id/book',auth,requireRole(...bookingRoles),(req,res)=>{const referralId=paramValue(req.params.id),referral=referrals.find(r=>r.id===referralId);if(!referral||!visibleReferralsFor(req.currentUser!).some(r=>r.id===referral.id))return res.status(404).json({error:'Referral not found in authorised scope'});if(!['ACCEPTED','SCHEDULED','PATIENT_NOTIFIED'].includes(referral.status))return res.status(409).json({error:'Referral must be accepted before an appointment can be booked'});const existing=appointments.find(a=>a.referralId===referral.id&&!['CANCELLED','NO_SHOW'].includes(a.status));if(existing)return res.status(409).json({error:'An active appointment already exists for this referral',appointment:appointmentView(existing)});const startAt=String(req.body?.startAt||'');if(!Number.isFinite(Date.parse(startAt))||Date.parse(startAt)<Date.now())return res.status(400).json({error:'A valid future appointment time is required'});if(referral.requiresBed&&referral.bedType&&!reserveBed(referral.destinationFacilityId,referral.bedType))return res.status(409).json({error:`No synthetic ${referral.bedType.toLowerCase().replace('_',' ')} bed is available at ${facilityName(referral.destinationFacilityId)}`,alternatives:alternativesFor(referral.service,referral.bedType)});const appt:Appointment={id:`appt-${Date.now()}`,patientId:referral.patientId,facilityId:referral.destinationFacilityId,referralId:referral.id,service:referral.service,startAt:new Date(startAt).toISOString(),durationMinutes:Math.min(240,Math.max(15,Number(req.body?.durationMinutes||30))),status:'BOOKED',bookedBy:req.currentUser!.displayName,bookingSource:'UI',requiresBed:Boolean(referral.requiresBed),bedType:referral.bedType,note:'Booked from accepted referral',createdAt:nowIso(),updatedAt:nowIso()};appointments.push(appt);referral.appointmentAt=appt.startAt;referral.status='SCHEDULED';referral.updatedAt=appt.updatedAt;referral.events.unshift({id:randomUUID(),at:appt.updatedAt,actor:req.currentUser!.displayName,from:'ACCEPTED',to:'SCHEDULED',note:`Appointment booked for ${appt.startAt}`,source:'UI'});addNotification({kind:'APPOINTMENT',priority:'MEDIUM',title:'Referral appointment booked',message:`${patientName(referral.patientId)} — ${referral.service} booked at ${facilityName(referral.destinationFacilityId)}.`,patientId:referral.patientId,facilityId:referral.destinationFacilityId,actionView:'appointments'});logAudit(req.currentUser!.displayName,'referral.appointment.book','Referral',referral.id,'UI');res.status(201).json({appointment:appointmentView(appt),referral:referralView(referral)})});
const appointmentTransitions:Record<AppointmentStatus,AppointmentStatus[]>={REQUESTED:['BOOKED','CANCELLED'],BOOKED:['CHECKED_IN','CANCELLED','NO_SHOW'],CHECKED_IN:['COMPLETED'],COMPLETED:[],CANCELLED:[],NO_SHOW:['BOOKED','CANCELLED']};
app.post('/api/appointments/:id/status',auth,(req,res)=>{const appointmentId=paramValue(req.params.id),appt=appointments.find(a=>a.id===appointmentId);if(!appt||!visibleAppointmentsFor(req.currentUser!).some(a=>a.id===appt.id))return res.status(404).json({error:'Appointment not found in authorised scope'});const to=String(req.body?.status||'') as AppointmentStatus;if(!appointmentTransitions[appt.status]?.includes(to))return res.status(409).json({error:`Invalid appointment transition from ${appt.status} to ${to}`});const role=req.currentUser!.role;if(role==='PATIENT'&&to!=='CANCELLED')return res.status(403).json({error:'Patient role may cancel but not clinically progress an appointment'});if(!['ADMIN','SPECIALIST','NURSE','COORDINATOR','PATIENT_NAVIGATOR','CLINICIAN','PATIENT'].includes(role))return res.status(403).json({error:'Role is not authorised to manage appointments'});const from=appt.status;if(to==='CANCELLED'&&appt.requiresBed)releaseReservedBed(appt.facilityId,appt.bedType);if(to==='CHECKED_IN'&&appt.requiresBed)checkInBed(appt.facilityId,appt.bedType);if(to==='COMPLETED'&&appt.requiresBed)dischargeBed(appt.facilityId,appt.bedType);appt.status=to;appt.updatedAt=nowIso();addNotification({kind:'APPOINTMENT',priority:to==='NO_SHOW'?'HIGH':'MEDIUM',title:`Appointment ${to.toLowerCase().replace('_',' ')}`,message:`${patientName(appt.patientId)} — ${appt.service} appointment status changed to ${to.toLowerCase().replace('_',' ')}.`,patientId:appt.patientId,facilityId:appt.facilityId,actionView:'appointments'});logAudit(req.currentUser!.displayName,`appointment.${to.toLowerCase()}`,'Appointment',appt.id,'UI','SUCCESS',`${from} -> ${to}`);res.json({appointment:appointmentView(appt)})});

app.get('/api/notifications',auth,(req,res)=>{const list=visibleNotificationsFor(req.currentUser!).sort((a,b)=>Date.parse(b.createdAt)-Date.parse(a.createdAt));res.json({notifications:list.map(n=>({...n,read:n.readBy.includes(req.currentUser!.id)})),unread:list.filter(n=>!n.readBy.includes(req.currentUser!.id)).length,syntheticData:true})});
app.post('/api/notifications/:id/read',auth,(req,res)=>{const id=paramValue(req.params.id),n=visibleNotificationsFor(req.currentUser!).find(x=>x.id===id);if(!n)return res.status(404).json({error:'Notification not found in authorised scope'});if(!n.readBy.includes(req.currentUser!.id))n.readBy.push(req.currentUser!.id);res.json({ok:true,notification:{...n,read:true}})});
app.post('/api/notifications/read-all',auth,(req,res)=>{for(const n of visibleNotificationsFor(req.currentUser!)){if(!n.readBy.includes(req.currentUser!.id))n.readBy.push(req.currentUser!.id)}res.json({ok:true})});

app.get('/api/medication-vaccine',auth,(req,res)=>{const visible=patients.filter(p=>canReadPatient(req.currentUser!,p.id));const records=visible.map(p=>({patientId:p.id,patientName:`${p.firstName} ${p.surname}`,syntheticId:p.syntheticId,medications:p.medications.map(m=>({...m,reviewDueAt:new Date(Date.parse(m.recordedAt)+180*86400000).toISOString()})),vaccinations:vaccinations.filter(v=>v.patientId===p.id)}));const currentMeds=records.reduce((n,r)=>n+r.medications.filter((m:any)=>m.status!=='Stopped').length,0),vax=records.flatMap(r=>r.vaccinations);res.json({syntheticData:true,summary:{patients:records.length,currentMedications:currentMeds,vaccinesDue:vax.filter(v=>v.status==='DUE').length,vaccinesOverdue:vax.filter(v=>v.status==='OVERDUE').length},patients:records})});
app.post('/api/patients/:id/medications',auth,requireRole(...medicationWriteRoles),(req,res)=>{const patientId=paramValue(req.params.id),patient=patients.find(p=>p.id===patientId);if(!patient||!canReadPatient(req.currentUser!,patientId))return res.status(404).json({error:'Patient not found in authorised scope'});const label=String(req.body?.label||'').trim(),detail=String(req.body?.detail||'').trim();if(!label)return res.status(400).json({error:'Medication name and dose are required'});const item={id:`med-${Date.now()}`,label:label.slice(0,160),detail:detail.slice(0,300)||'Synthetic medication management entry',recordedAt:nowIso(),sourceFacility:req.currentUser!.facilityId?facilityName(req.currentUser!.facilityId):'CarePath Administration (Demo)',status:'Current'};patient.medications.unshift(item);addNotification({kind:'MEDICATION',priority:'MEDIUM',title:'Medication record updated',message:`${patientName(patientId)} — ${item.label} added to the synthetic longitudinal record.`,patientId,facilityId:req.currentUser!.facilityId||undefined,roles:['PHARMACIST','CLINICIAN'],actionView:'medication'});logAudit(req.currentUser!.displayName,'medication.add','Patient',patientId,'UI');res.status(201).json({medication:item})});
app.post('/api/patients/:id/medications/:medId/status',auth,requireRole(...medicationWriteRoles),(req,res)=>{const patientId=paramValue(req.params.id),medId=paramValue(req.params.medId),patient=patients.find(p=>p.id===patientId);if(!patient||!canReadPatient(req.currentUser!,patientId))return res.status(404).json({error:'Patient not found in authorised scope'});const med=patient.medications.find(m=>m.id===medId);if(!med)return res.status(404).json({error:'Medication not found'});const status=String(req.body?.status||'');if(!['Current','Stopped','On hold'].includes(status))return res.status(400).json({error:'Invalid medication status'});med.status=status;logAudit(req.currentUser!.displayName,'medication.status.update','Medication',med.id,'UI');res.json({medication:med})});
app.post('/api/patients/:id/vaccinations',auth,requireRole(...vaccineWriteRoles),(req,res)=>{const patientId=paramValue(req.params.id),patient=patients.find(p=>p.id===patientId);if(!patient||!canReadPatient(req.currentUser!,patientId))return res.status(404).json({error:'Patient not found in authorised scope'});const vaccine=String(req.body?.vaccine||'').trim(),dose=String(req.body?.dose||'').trim(),nextDueAt=req.body?.nextDueAt?String(req.body.nextDueAt):undefined;if(!vaccine||!dose)return res.status(400).json({error:'Vaccine and dose are required'});const nextMs=nextDueAt?Date.parse(nextDueAt):NaN,status:VaccineRecord['status']=Number.isFinite(nextMs)?(nextMs<Date.now()?'OVERDUE':nextMs<=Date.now()+30*86400000?'DUE':'COMPLETE'):'COMPLETE';const record:VaccineRecord={id:`vax-${Date.now()}`,patientId,vaccine:vaccine.slice(0,140),dose:dose.slice(0,80),administeredAt:nowIso(),administeredFacility:req.currentUser!.facilityId?facilityName(req.currentUser!.facilityId):'CarePath Administration (Demo)',nextDueAt:Number.isFinite(nextMs)?new Date(nextMs).toISOString():undefined,status,synthetic:true};vaccinations.unshift(record);addNotification({kind:'VACCINE',priority:status==='OVERDUE'?'HIGH':'MEDIUM',title:'Vaccination record updated',message:`${patientName(patientId)} — ${record.vaccine} ${record.dose} recorded.`,patientId,facilityId:req.currentUser!.facilityId||undefined,roles:['CLINICIAN','NURSE','PHARMACIST'],actionView:'medication'});logAudit(req.currentUser!.displayName,'vaccination.add','Patient',patientId,'UI');res.status(201).json({vaccination:record})});

app.get('/api/ambulances',auth,(req,res)=>{const visible=req.currentUser!.role==='PATIENT'?ambulances.filter(a=>visibleTransfersFor(req.currentUser!).some(t=>t.ambulanceId===a.id)):ambulances;res.json({syntheticData:true,disclaimer:'Synthetic ambulance availability and ETA data for hackathon demonstration only; not a live EMS dispatch feed.',ambulances:visible.map(ambulanceView),summary:{available:ambulances.filter(a=>a.status==='AVAILABLE').length,dispatched:ambulances.filter(a=>a.status==='DISPATCHED').length,maintenance:ambulances.filter(a=>a.status==='MAINTENANCE').length,total:ambulances.length}})});
app.get('/api/transfers',auth,(req,res)=>res.json({syntheticData:true,transfers:visibleTransfersFor(req.currentUser!).sort((a,b)=>Date.parse(b.updatedAt)-Date.parse(a.updatedAt)).map(transferView)}));
app.post('/api/transfers',auth,requireRole(...transferWriteRoles),(req,res)=>{const patientId=String(req.body?.patientId||''),referralId=req.body?.referralId?String(req.body.referralId):undefined,pickupFacilityId=String(req.body?.pickupFacilityId||''),destinationFacilityId=String(req.body?.destinationFacilityId||''),priority=String(req.body?.priority||'ROUTINE') as TransferPriority,requiredLevel=String(req.body?.requiredLevel||'BASIC') as AmbulanceType,scheduledAt=String(req.body?.scheduledAt||nowIso());if(!canReadPatient(req.currentUser!,patientId))return res.status(403).json({error:'Patient is outside authorised scope'});if(!facilities.some(f=>f.id===pickupFacilityId)||!facilities.some(f=>f.id===destinationFacilityId))return res.status(400).json({error:'Valid pickup and destination facilities are required'});if(!['ROUTINE','URGENT','EMERGENCY'].includes(priority))return res.status(400).json({error:'Invalid transfer priority'});if(!['BASIC','ADVANCED','ICU','NEONATAL'].includes(requiredLevel))return res.status(400).json({error:'Invalid ambulance level'});const referral=referralId?referrals.find(r=>r.id===referralId):undefined;if(referralId&&!referral)return res.status(404).json({error:'Referral not found'});if(referral?.requiresBed&&referral.bedType&&availableBeds(destinationFacilityId,referral.bedType)<1)return res.status(409).json({error:`Patient transfer blocked: no synthetic ${referral.bedType.toLowerCase().replace('_',' ')} bed is available at ${facilityName(destinationFacilityId)}`,alternatives:alternativesFor(referral.service,referral.bedType)});const transfer:TransferRequest={id:`trn-${Date.now()}`,patientId,referralId,pickupFacilityId,destinationFacilityId,priority,requiredLevel,scheduledAt:Number.isFinite(Date.parse(scheduledAt))?new Date(scheduledAt).toISOString():nowIso(),status:'REQUESTED',requestedBy:req.currentUser!.displayName,note:String(req.body?.note||'').slice(0,400)||undefined,createdAt:nowIso(),updatedAt:nowIso(),synthetic:true};const ambulance=findAmbulance(requiredLevel);if(ambulance)assignAmbulance(transfer,ambulance);transfers.unshift(transfer);addNotification({kind:'TRANSFER',priority:priority==='EMERGENCY'?'HIGH':'MEDIUM',title:ambulance?'Ambulance assigned':'Transfer waiting for ambulance',message:ambulance?`${patientName(patientId)} assigned to ${ambulance.callSign}; synthetic ETA ${ambulance.etaMinutes} min.`:`${patientName(patientId)} transfer request is waiting for a compatible ambulance.`,patientId,facilityId:destinationFacilityId,roles:['COORDINATOR','NURSE','MANAGER','PATIENT_NAVIGATOR'],actionView:'transfers'});logAudit(req.currentUser!.displayName,'transfer.request','Transfer',transfer.id,'UI');res.status(201).json({transfer:transferView(transfer),autoAssigned:Boolean(ambulance)})});
app.post('/api/transfers/:id/assign',auth,requireRole(...transferManageRoles),(req,res)=>{const id=paramValue(req.params.id),transfer=transfers.find(t=>t.id===id);if(!transfer||!visibleTransfersFor(req.currentUser!).some(t=>t.id===id))return res.status(404).json({error:'Transfer not found in authorised scope'});if(!['REQUESTED','ASSIGNED'].includes(transfer.status))return res.status(409).json({error:'Transfer cannot be assigned in its current state'});const requestedId=String(req.body?.ambulanceId||''),ambulance=requestedId?ambulances.find(a=>a.id===requestedId):findAmbulance(transfer.requiredLevel);if(!ambulance||!ambulanceCanServe(ambulance,transfer.requiredLevel))return res.status(409).json({error:'No compatible synthetic ambulance is currently available'});if(transfer.ambulanceId&&transfer.ambulanceId!==ambulance.id)releaseAmbulance(transfer.ambulanceId);assignAmbulance(transfer,ambulance);addNotification({kind:'TRANSFER',priority:transfer.priority==='EMERGENCY'?'HIGH':'MEDIUM',title:'Ambulance assigned',message:`${patientName(transfer.patientId)} assigned to ${ambulance.callSign}; synthetic ETA ${ambulance.etaMinutes} min.`,patientId:transfer.patientId,facilityId:transfer.destinationFacilityId,actionView:'transfers'});logAudit(req.currentUser!.displayName,'transfer.assign_ambulance','Transfer',transfer.id,'UI');res.json({transfer:transferView(transfer)})});
const transferTransitions:Record<TransferStatus,TransferStatus[]>={REQUESTED:['ASSIGNED','CANCELLED'],ASSIGNED:['EN_ROUTE','CANCELLED'],EN_ROUTE:['PATIENT_ON_BOARD','CANCELLED'],PATIENT_ON_BOARD:['ARRIVED'],ARRIVED:['COMPLETED'],COMPLETED:[],CANCELLED:[]};
app.post('/api/transfers/:id/status',auth,requireRole(...transferManageRoles),(req,res)=>{const id=paramValue(req.params.id),transfer=transfers.find(t=>t.id===id);if(!transfer||!visibleTransfersFor(req.currentUser!).some(t=>t.id===id))return res.status(404).json({error:'Transfer not found in authorised scope'});const status=String(req.body?.status||'') as TransferStatus;if(!transferTransitions[transfer.status]?.includes(status))return res.status(409).json({error:`Invalid transfer transition from ${transfer.status} to ${status}`});const from=transfer.status;transfer.status=status;transfer.updatedAt=nowIso();if(['COMPLETED','CANCELLED'].includes(status))releaseAmbulance(transfer.ambulanceId);addNotification({kind:'TRANSFER',priority:['CANCELLED'].includes(status)?'HIGH':'MEDIUM',title:'Patient transfer updated',message:`${patientName(transfer.patientId)} transfer changed from ${from.toLowerCase().replaceAll('_',' ')} to ${status.toLowerCase().replaceAll('_',' ')}.`,patientId:transfer.patientId,facilityId:transfer.destinationFacilityId,actionView:'transfers'});logAudit(req.currentUser!.displayName,`transfer.${status.toLowerCase()}`,'Transfer',transfer.id,'UI');res.json({transfer:transferView(transfer)})});
app.post('/api/ambulances/:id/status',auth,requireRole('ADMIN','COORDINATOR','MANAGER'),(req,res)=>{const id=paramValue(req.params.id),ambulance=ambulances.find(a=>a.id===id);if(!ambulance)return res.status(404).json({error:'Ambulance not found'});const status=String(req.body?.status||'') as AmbulanceStatus;if(!['AVAILABLE','MAINTENANCE'].includes(status))return res.status(400).json({error:'Manual fleet status may be AVAILABLE or MAINTENANCE only'});if(ambulance.status==='DISPATCHED'&&transfers.some(t=>t.ambulanceId===ambulance.id&&!['COMPLETED','CANCELLED'].includes(t.status)))return res.status(409).json({error:'Cannot manually change a dispatched ambulance with an active transfer'});ambulance.status=status;ambulance.updatedAt=nowIso();logAudit(req.currentUser!.displayName,'ambulance.status.update','Ambulance',ambulance.id,'UI');res.json({ambulance:ambulanceView(ambulance)})});

app.get('/api/outcomes',auth,(req,res)=>{if(req.currentUser!.role==='PATIENT')return res.status(403).json({error:'Outcome analytics are not available in the patient role'});const scoped=managementRoles.includes(req.currentUser!.role)?referrals:visibleReferralsFor(req.currentUser!);res.json({syntheticData:true,disclaimer:'Observed synthetic outcomes only. These values are not risk-adjusted, do not represent real hospitals and must not be interpreted as a clinical quality ranking.',methodology:'Shows referral volume and recorded synthetic outcomes. A production comparison would require validated outcome definitions, case-mix/risk adjustment, confidence intervals, minimum sample sizes and governance review.',facilities:outcomeSummary(scoped)})});
app.get('/api/caregaps',auth,(req,res)=>{if(req.currentUser!.role==='PATIENT')return res.status(403).json({error:'Operational care-gap queue is not available in the patient role'});const scopedReferrals=visibleReferralsFor(req.currentUser!),scopedPatients=patients.filter(p=>canReadPatient(req.currentUser!,p.id)),scopedTransfers=visibleTransfersFor(req.currentUser!),gaps:any[]=[];for(const r of scopedReferrals){if(['SUBMITTED','RECEIVED','INFO_REQUESTED'].includes(r.status)&&Date.now()-Date.parse(r.updatedAt)>24*3600000)gaps.push({id:`gap-ref-${r.id}`,type:'REFERRAL_DELAY',severity:'HIGH',patientId:r.patientId,patientName:patientName(r.patientId),detail:`Referral ${r.id} has been waiting more than 24 hours`,action:'Review referral ownership and next permitted action'});if(r.status==='MISSED'||r.status==='FOLLOWUP_REQUIRED')gaps.push({id:`gap-follow-${r.id}`,type:'FOLLOW_UP',severity:'MEDIUM',patientId:r.patientId,patientName:patientName(r.patientId),detail:`Referral ${r.id} requires follow-up`,action:'Confirm patient contact and rescheduling workflow'});if(r.requiresBed&&r.bedType&&availableBeds(r.destinationFacilityId,r.bedType)===0)gaps.push({id:`gap-bed-${r.id}`,type:'CAPACITY_CONSTRAINT',severity:'HIGH',patientId:r.patientId,patientName:patientName(r.patientId),detail:`No synthetic ${r.bedType.toLowerCase().replace('_',' ')} bed is currently available at ${facilityName(r.destinationFacilityId)}`,action:'Review destination capacity and authorised alternatives'})}for(const t of scopedTransfers){if(t.status==='REQUESTED'&&Date.now()-Date.parse(t.createdAt)>30*60000)gaps.push({id:`gap-transfer-${t.id}`,type:'TRANSFER_DELAY',severity:'HIGH',patientId:t.patientId,patientName:patientName(t.patientId),detail:`Transfer ${t.id} has no assigned ambulance after 30 minutes`,action:'Review ambulance availability or escalation route'})}for(const p of scopedPatients.slice(0,35)){if(!p.results.length)gaps.push({id:`gap-data-${p.id}`,type:'DATA_COMPLETENESS',severity:'LOW',patientId:p.id,patientName:`${p.firstName} ${p.surname}`,detail:'No diagnostic result is present in the current synthetic longitudinal record',action:'Verify whether a result exists in an authorised source system'})}for(const v of vaccinations.filter(v=>v.status==='OVERDUE'&&canReadPatient(req.currentUser!,v.patientId)).slice(0,10)){gaps.push({id:`gap-vax-${v.id}`,type:'VACCINE_OVERDUE',severity:'MEDIUM',patientId:v.patientId,patientName:patientName(v.patientId),detail:`${v.vaccine} ${v.dose} is overdue in the synthetic record`,action:'Confirm immunisation status and authorised follow-up'})}res.json({syntheticData:true,definition:'Operational, capacity, transfer, medication/vaccine and information-continuity gaps only; not clinical diagnoses.',gaps:gaps.slice(0,70)})});

app.get('/api/audit',auth,requireRole('AUDITOR','MANAGER','ADMIN'),(_req,res)=>res.json({auditEvents}));
app.get('/api/admin/users',auth,requireRole('ADMIN'),(_req,res)=>res.json({users:users.map(safeUser),roles:[...new Set(users.map(u=>u.role))]}));
app.get('/api/admin/openai-settings',auth,requireRole('ADMIN'),(_req,res)=>res.json(getOpenAISettings()));
app.put('/api/admin/openai-settings',auth,requireRole('ADMIN'),(req,res)=>{const settings=updateOpenAISettings({enabled:req.body?.enabled,model:req.body?.model,baseUrl:req.body?.baseUrl,apiKey:req.body?.apiKey,allowSyntheticDemoData:req.body?.allowSyntheticDemoData});logAudit(req.currentUser!.displayName,'admin.openai_settings.update','AISettings','openai','UI');res.json(settings)});
app.post('/api/admin/openai-settings/test',auth,requireRole('ADMIN'),async(req,res)=>{try{const result=await testOpenAISettings();logAudit(req.currentUser!.displayName,'admin.openai_settings.test','AISettings','openai','UI',result.ok?'SUCCESS':'DENIED',result.message);res.status(result.ok?200:400).json(result)}catch(error:any){res.status(502).json({ok:false,message:error?.message||'OpenAI connection test failed'})}});

app.post('/api/ayanda',auth,async(req,res)=>{const input=String(req.body?.input||'').slice(0,1000);if(!input.trim())return res.status(400).json({error:'Input is required'});const response=await answerAyanda(input,{patients:patients.filter(p=>canReadPatient(req.currentUser!,p.id)),referrals:visibleReferralsFor(req.currentUser!),facilities,ambulances});logAudit(req.currentUser!.displayName,'ai.query','AIInteraction',randomUUID(),req.body?.source==='VOICE'?'VOICE':'AI');res.json(response)});
app.post('/api/ayanda/execute',auth,requireRole('CLINICIAN','ADMIN'),(req,res)=>{if(req.body?.confirmed!==true)return res.status(400).json({error:'Explicit confirmation is required'});const action=req.body?.action;if(action?.tool!=='create_referral_draft'||!action.patientId||!canReadPatient(req.currentUser!,action.patientId))return res.status(400).json({error:'Unsupported, invalid or unauthorised action'});const destination=facilities.find(f=>f.id===action.destinationFacilityId);if(!destination)return res.status(400).json({error:'Invalid destination'});const bedType=bedTypeForService(String(action.service||''));if(bedType&&availableBeds(destination.id,bedType)<1)return res.status(409).json({error:`No synthetic ${bedType.toLowerCase().replace('_',' ')} bed is available at ${destination.name}`,alternatives:alternativesFor(String(action.service||''),bedType)});const referral:Referral={id:`ref-${Date.now()}`,patientId:action.patientId,service:String(action.service||'Specialist review').slice(0,120),reason:`AI-assisted draft for ${String(action.service||'specialist').toLowerCase()} review; clinician must verify clinical rationale`,sourceFacilityId:req.currentUser!.facilityId||'fac-clinic-1',destinationFacilityId:destination.id,owner:req.currentUser!.displayName,status:'DRAFT',priority:'ROUTINE',createdAt:nowIso(),updatedAt:nowIso(),requiresBed:Boolean(bedType),bedType,events:[{id:randomUUID(),at:nowIso(),actor:req.currentUser!.displayName,to:'DRAFT',note:'Draft created after explicit human confirmation and capacity check',source:'AI'}]};referrals.unshift(referral);logAudit(req.currentUser!.displayName,'ai.tool.create_referral_draft','Referral',referral.id,'AI');res.status(201).json({referral:referralView(referral),text:'Referral draft created after the synthetic destination-capacity check. It remains a draft until an authorised clinician reviews and submits it.'})});

if(production){const __dirname=path.dirname(fileURLToPath(import.meta.url)),webDist=path.resolve(__dirname,'../../web/dist');app.use(express.static(webDist));app.get('*splat',(_req,res)=>res.sendFile(path.join(webDist,'index.html')))}
app.listen(port,()=>console.log(`CarePath API v0.4 listening on ${port}`));
